{{- if .Values.internalSecrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: document-database-pg-secret-esm
  labels:
    app.kubernetes.io/name: document-database-pg-secret-esm
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  # For super user and password
  super-user: {{ "postgres" | b64enc | quote }}
  super-pwd: {{ "UDBzdGdyZVNRTDEx" | quote }}

  # For metrics user and password
  metrics-user: {{ "exporter" | b64enc | quote }}
  metrics-pwd: {{ "ZXhwb3J0ZXI=" | quote }}

  # For replication user and password
  replica-user: {{ "replica" | b64enc | quote }}
  replica-pwd: {{ "cmVwbGljYQ==" | quote }}
{{- end -}}
